### ISSUE TITLE
Adding Responsive Clock

### ISSUE THREAD

**Issue by YOGDEV** [knockcat/Hacktoberfest-2022#14]
using html ,css and javascript.

**Comment by knockcat** [comment]
Go ahead.

**Comment by devocoe** [comment]
hey, can you please assign this issue to me

**Comment by s4shantanu** [comment]
Hey, @knockcat Can you please assign me this task?

**Comment by knockcat** [comment]
@s4shantanu  This issue is solved brother, I forgot to close. You can make a pull request of your any development project.
