### ISSUE TITLE
Add development projects. 

### ISSUE THREAD

**Issue by knockcat** [knockcat/Hacktoberfest-2022#18]
Add pull request to any of your development projects.

**Comment by ElectricPlant19** [comment]
What exactly does it mean ? Do i just fork and add a new folder of any of my projects ?

**Comment by knockcat** [comment]
@ElectricPlant19 yes, later you can raise issues if they have.

**Comment by SJ-Kumar** [comment]
I would like to add my frontend login validation page. Please assign.

**Comment by knockcat** [comment]
@SJ-Kumar i have assigned you.

**Comment by ShivanshDengla** [comment]
@knockcat hey, i made a pull request for a portfolio website.
Thanks

**Comment by knockcat** [comment]
Thanks @ShivanshDengla hope your contribution helps other opensource peers.

**Comment by harshiitsingh** [comment]
Hey @knockcat, can you please assign this issue to me?

**Comment by knockcat** [comment]
@harshiitsingh create a new issue regarding what you want to add, I will assign that to you.

**Comment by harshiitsingh** [comment]
> @harshiitsingh create a new issue regarding what you want to add, I will assign that to you.

Thank You. I would like to add a CNN based Project.

**Comment by knockcat** [comment]
yes go ahead @harshiitsingh

**Comment by C-V-Anish** [comment]
Hey @knockcat , I have made a pull request for some of my Automation works.
Thank you.

**Comment by zaidsidd360** [comment]
Hey @knockcat could you please assign me? I would like to add an interactive react app which will help people get started with the git command line interface.
