### ISSUE TITLE
Calculator App

### ISSUE THREAD

**Issue by m3g4n127001** [knockcat/Hacktoberfest-2022#28]
Hey!
I am interested to implement a Calculator App using JS and add that project to this repo.
Can you please assign this to me?
Thanks :)

**Comment by knockcat** [comment]
Yes go ahead with the project.

**Comment by Sengar123** [comment]
Hello Sir, I am interested in this project.
Can you please assign this to me?
Thanks :)

**Comment by knockcat** [comment]
@Sengar123 Since this project is already assigned so you can contribute some other.

**Comment by knockcat** [comment]
@Sengar123 @m3g4n127001 you can go with this project I am assigning to both of you this project.
the one who send a pull request first I will add his/her contribution.
