### ISSUE TITLE
TicTacToe Game

### ISSUE THREAD

**Issue by thanmayee43** [knockcat/Hacktoberfest-2022#35]
Hi, I am interested to implement TicTacToe game using JS and add to this repo.
Could you please assign me this project?
Thanks!!

**Comment by knockcat** [comment]
Yes brother go ahead with the project.

**Comment by cereal-hecker** [comment]
hey, i can implement TicTacToe in C, pls assign me this

**Comment by knockcat** [comment]
@cereal-hecker since this project is already assigned you can contribute some other project.

**Comment by knockcat** [comment]
@thanmayee43 are you willing to take this project or I assign to someone else.

**Comment by thanmayee43** [comment]
I hv done and uploaded as well.
